services:
  postgres:
    image: postgres:18-alpine
    container_name: stapelfeed_db_srv
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - stapelfeed_pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: stapelfeed_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: stapelfeed_grafana
    ports:
      - "3000:3000"
    volumes:
      - stapelfeed_grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  stapelfeed_pgdata_prod:
  stapelfeed_grafana_data:
